spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dianping?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&allowPublicKeyRetrieval=true

    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  redis:
    host: 192.168.56.129
    port: 6379
server:
  port: 8081
